apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiMnh3YjNScmFXNDZaMmh3WDIxeFdUWnlhV0p6TUdWNFVXRnhkbFZqYjB0S01sUkxkM2h1WkVFMlVUSlZUVEJwZUE9PSIKICAgICAgICB9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
